const fs = require('fs');
const path = require('path');

const target = path.join(__dirname, '..', 'packages', 'extension', 'entrypoints', 'popup', 'App.vue');
let content = fs.readFileSync(target, 'utf8');

const replacements = [
  ['<!-- 首页 -->', '<!-- Home View -->'],
  ['<h1 class="header-title">Chrome MCP Server</h1>', '<h1 class="header-title">NexusAI Browser Agent</h1>'],
  ['<!-- 服务配置卡片 -->', '<!-- Bridge Gateway Configuration Card -->'],
  ['<!-- 快捷工具卡片 -->', '<!-- Quick Directives Card -->'],
  ['<h2 class="section-title">快捷工具</h2>', '<h2 class="section-title">Quick Directives</h2>'],
  ['data-tooltip="录制功能开发中"', 'data-tooltip="Workflow recording in active development"'],
  ['data-tooltip="开启页面编辑模式"', 'data-tooltip="Toggle Interactive Page Inspector"'],
  ['data-tooltip="开启元素标注"', 'data-tooltip="Toggle Element Coordinate Marker"'],
  ['<!-- 管理入口卡片 -->', '<!-- Workspace Entry Panels -->'],
  ['<h2 class="section-title">管理入口</h2>', '<h2 class="section-title">Workspace Panels</h2>'],
  ['<span class="entry-title">智能助手</span>', '<span class="entry-title">Autonomous Agent</span>'],
  ['<span class="entry-desc">AI Agent 对话与任务</span>', '<span class="entry-desc">Agent directives & task execution</span>'],
  ['工作流管理', 'Workflow Engine'],
  ['<span class="entry-desc">录制与回放自动化流程</span>', '<span class="entry-desc">Automated workflow replay</span>'],
  ['<span class="entry-title">元素标注管理</span>', '<span class="entry-title">Coordinate Map</span>'],
  ['<span class="entry-desc">管理页面元素标注</span>', '<span class="entry-desc">Inspect visual element boundaries</span>'],
  ['<span class="entry-title">本地模型</span>', '<span class="entry-title">Neural Vector Engine</span>'],
  ['<span class="entry-desc">语义引擎与模型管理</span>', '<span class="entry-desc">Transformer models & semantic cache</span>'],
  ['<p class="footer-text">chrome mcp server for ai</p>', '<p class="footer-text">NexusAI Autonomous Browser Runtime</p>'],
  ['<!-- 本地模型二级页面 -->', '<!-- Local Model Sub-view -->'],
  ['<!-- 侧边栏承担工作流管理；编辑器在独立窗口中打开 -->', '<!-- Sidepanel manages workflows; editor opens in separate window -->'],
  ['<span>{{ comingSoonToast.feature }} 功能开发中，敬请期待</span>', '<span>{{ comingSoonToast.feature }} is under active development.</span>'],
  ['// AgentChat theme - 从preload中获取，保持与sidepanel一致', '// Agent theme - synchronized with sidepanel preference'],
  ['// 当前视图状态：首页 or 本地模型页', '// Current active view: home or local-model'],
  ['// Flow editor在独立窗口中打开；在popup不再展示繁杂列表', '// Flow editor operates in standalone window'],
  ['// 运行记录与覆盖项在侧边栏页面查看', '// Execution history viewable in sidepanel'],
  ["// TODO: 录制回放功能开发中，暂时拦截\n  showComingSoonToast('录制回放');", "showComingSoonToast('Workflow Recording');"],
  ["showComingSoonToast('录制回放');", "showComingSoonToast('Workflow Recording');"],
  ["//     meta: { name: '新录制' },", "//     meta: { name: 'New Recording' },"],
  ["//   console.error('开始录制失败:', e);", "//   console.error('Start recording failed:', e);"],
  ["//   console.error('停止录制失败:', e);", "//   console.error('Stop recording failed:', e);"],
  ["console.warn('回放失败');", "console.warn('Workflow replay failed');"],
  ['// 打开独立编辑窗口并定位失败节点', '// Focus failed step in builder window'],
  ["console.error('回放失败:', e);", "console.error('Workflow replay failed:', e);"],
  ['// 旧的“克隆/发布/定时/覆盖项”在侧边栏或编辑器中处理', '// Overrides and schedules managed in sidepanel'],
  ['const nativeServerPort = ref<number>(12306);', 'const nativeServerPort = ref<number>(12307);'],
  ["'streamable-mcp-server':", "'nexus-browser':"],
  ["type: 'streamable-http',", "type: 'streamableHttp',"],
  ["// TODO: 工作流功能开发中，暂时拦截\n  showComingSoonToast('工作流管理');", "showComingSoonToast('Workflow Engine');"],
  ["showComingSoonToast('工作流管理');", "showComingSoonToast('Workflow Engine');"],
  ["console.warn('切换网页编辑模式失败:', error);", "console.warn('Failed to toggle web editor mode:', error);"],
  ['// 获取当前活动tab', '// Query active tab in current window'],
  ["console.warn('无法获取当前tab');", "console.warn('Unable to determine active tab');"],
  ['// 向background发送消息，启动元素标注', '// Dispatch element marker initialization to background worker'],
  ["console.warn('开启元素标注失败:', error);", "console.warn('Failed to start element marker:', error);"],
  ["console.error('保存语义引擎状态失败:', error);", "console.error('Failed to persist semantic engine state:', error);"],
  ["console.error('检测 Native 连接状态失败:', error);", "console.error('Failed to query native link status:', error);"],
  ["console.error('检测服务器状态失败:', error);", "console.error('Failed to query server health:', error);"],
  ["console.error('刷新服务器状态失败:', error);", "console.error('Failed to refresh server status:', error);"],
  ["console.error('复制配置失败:', error);", "console.error('Failed to copy config:', error);"],
  ['`尝试连接到端口: ${nativeServerPort.value}`', '`Attempting bridge link on port: ${nativeServerPort.value}`'],
  ["console.log('连接成功:', response);", "console.log('Bridge link established:', response);"],
  ["console.error('连接失败:', response);", "console.error('Bridge link rejected:', response);"],
  ["console.error('测试连接失败:', error);", "console.error('Bridge probe error:', error);"],
  ["console.error('❌ 加载模型偏好失败:', error);", "console.error('Failed to load model preferences:', error);"],
  ["console.error('保存模型偏好失败:', error);", "console.error('Failed to save model preferences:', error);"],
  ["console.error('保存版本偏好失败:', error);", "console.error('Failed to save version preference:', error);"],
  ['`端口偏好已保存: ${port}`', '`Port preference persisted: ${port}`'],
  ["console.error('保存端口偏好失败:', error);", "console.error('Failed to persist port preference:', error);"],
  ['`端口偏好已加载: ${result.nativeServerPort}`', '`Port preference loaded: ${result.nativeServerPort}`'],
  ["console.error('加载端口偏好失败:', error);", "console.error('Failed to load port preference:', error);"],
  ["console.error('保存模型状态失败:', error);", "console.error('Failed to persist model state:', error);"],
  ["console.error('获取模型状态失败:', error);", "console.error('Failed to query model state:', error);"],
  ["'模型切换成功:'", "'Transformer model switched successfully:'"],
  ["console.error('模型切换失败:', error);", "console.error('Model switch failed:', error);"],
  ["const errorMessage = error?.message || '未知错误';", "const errorMessage = error?.message || 'Unknown runtime error';"],
  ['// 初始化主题', '// Initialize theme'],
  ['/* 快捷工具icon按钮样式 */', '/* Quick action button styles */'],
  ['/* 录制按钮 - 红色 */', '/* Record button */'],
  ['/* 录制中状态 - 脉冲动画 */', '/* Active recording pulse animation */'],
  ['/* 停止按钮 - 深红色 */', '/* Stop button */'],
  ['/* 编辑按钮 - 蓝色 */', '/* Web editor button */'],
  ['/* 标注按钮 - 绿色 */', '/* Element marker button */'],
  ['/* Coming Soon 按钮样式 */', '/* Coming soon badge style */'],
  ['/* 首页视图 */', '/* Home view layout */'],
  ['/* 管理入口卡片样式 */', '/* Workspace entry panel styles */'],
];

for (const [from, to] of replacements) {
  content = content.replaceAll(from, to);
}

fs.writeFileSync(target, content, 'utf8');
console.log('App.vue cleaned successfully.');
